# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  # Build tags to use
  build-tags:
    - checkmk_all
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions
    check-type-assertions: false

issues:
  # Don't limit the number of issues
  max-issues-per-linter: 0
  max-same-issues: 0
