# Created by WATO
# encoding: utf-8

wato_host_attrs = []
if type(wato_host_attrs) != list:
    wato_host_attrs = []
wato_host_attrs += [{'add_custom_macro': True,
  'help': u'Set the Proxy Port',
  'name': 'proxy_port',
  'show_in_table': True,
  'title': u'Proxy Port',
  'topic': 'address',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'Configure Round Trip Time (RTT) used for PING checks. When threshold breached, the check will enter WARNING state.',
  'name': 'rtt_warn',
  'show_in_table': False,
  'title': u'RTT WARNING',
  'topic': 'basic',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'Configure Round Trip Time (RTT) used for PING checks. When threshold breached, the check will enter CRITICAL state.',
  'name': 'rtt_crit',
  'show_in_table': False,
  'title': u'RTT CRITICAL',
  'topic': 'basic',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'',
  'name': 'device_description',
  'show_in_table': True,
  'title': u'Device Description',
  'topic': 'basic',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'Service Now group that the alert ticket should be assigned to',
  'name': 'snowgroup',
  'show_in_table': False,
  'title': u'Service Now Group',
  'topic': 'alerting',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'Action to carry out when snow ticket has been raised to the appropriate queue',
  'name': 'snow_action',
  'show_in_table': False,
  'title': u'Service Now Action',
  'topic': 'alerting',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'',
  'name': 'device_make',
  'show_in_table': False,
  'title': u'Device Make',
  'topic': 'basic',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'',
  'name': 'notes',
  'show_in_table': False,
  'title': u'Notes',
  'topic': 'basic',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'',
  'name': 'site_address',
  'show_in_table': False,
  'title': u'Site Address',
  'topic': 'location',
  'type': 'TextAscii'},
 {'add_custom_macro': False,
  'help': u'',
  'name': 'display_name',
  'show_in_table': False,
  'title': u'Display Name (Legacy)',
  'topic': 'basic',
  'type': 'TextAscii'},
 {'add_custom_macro': False,
  'help': u'',
  'name': 'hsrp_state',
  'show_in_table': False,
  'title': u'HSRP State',
  'topic': 'custom_attributes',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'Set port for Custom TCP Check Rule, when label: check_tcp:true is set on host',
  'name': 'tcp_port',
  'show_in_table': False,
  'title': u'TCP Port',
  'topic': 'address',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'',
  'name': 'snowservice',
  'show_in_table': False,
  'title': u'Service Now Service',
  'topic': 'alerting',
  'type': 'TextAscii'},
 {'add_custom_macro': True,
  'help': u'Field to indicate if a Twilio Alert should be raised',
  'name': 'twilio',
  'show_in_table': False,
  'title': u'Twilio',
  'topic': 'alerting',
  'type': 'TextAscii'}]