#!/usr/bin/env python3
"""
Generate Docker Compose configurations for CheckMK testing.

Usage:
    ./scripts/generate-compose.py                    # Local multi-container
    ./scripts/generate-compose.py --mode=ci --version=2.4  # CI single container
    ./scripts/generate-compose.py --output=ci/       # Generate CI matrix files
    ./scripts/generate-compose.py --edition=raw      # Use free Raw Edition

Modes:
    local   - All versions in one compose file (default)
    ci      - Single version per file for parallel CI jobs
    matrix  - Generate all CI files for GitHub Actions matrix

Configuration:
    --site-id             CheckMK site name (default: test)
    --admin-password      Web UI password for cmkadmin (default: test123)
    --automation-password API password for automation user (default: testSecret123)
    --edition             CheckMK edition: enterprise or raw (default: enterprise)
    --port-base           Base port number, versions offset by 20/30/40 (default: 5000)

Credentials are available via container environment variables and labels:
    docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' <container>
"""

import argparse
import json
import os
import sys
from pathlib import Path

# Supported CheckMK versions (port offsets from base)
# The enterprise trial registry (registry.checkmk.com) retains only a rolling
# window of the most recent ~10 patch releases per branch, so these pins must be
# refreshed periodically as older patches age out of the window.
VERSIONS = {
    "2.2": {"full": "2.2.0p47", "port_offset": 20},
    "2.3": {"full": "2.3.0p48", "port_offset": 30},
    "2.4": {"full": "2.4.0p32", "port_offset": 40},
    "2.5": {"full": "2.5.0p12", "port_offset": 50},
}

# Docker registry URLs by edition
REGISTRIES = {
    "enterprise": "registry.checkmk.com/enterprise/check-mk-enterprise",
    "raw": "checkmk/check-mk-raw",
}

# Default configuration
DEFAULTS = {
    "site_id": "test",
    "admin_password": "test123",
    "automation_password": "testSecret123",
    "edition": "enterprise",
    "port_base": 5000,
}

COMPOSE_HEADER = """# Auto-generated Docker Compose for CheckMK testing
# Generated by: ./scripts/generate-compose.py
#
# Credentials are in container environment variables:
#   docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' <container> | grep CMK_
#
# API URL is in container labels:
#   docker inspect --format '{{index .Config.Labels "checkmk.api_url"}}' <container>

"""

def generate_service(version: str, info: dict, config: dict, port_offset: int = 0, include_custom_attrs: bool = True) -> dict:
    """Generate a single service definition."""
    port = config["port_base"] + info["port_offset"] + port_offset
    full_version = info["full"]
    site_id = config["site_id"]
    registry = REGISTRIES[config["edition"]]

    service = {
        "image": f"{registry}:{full_version}",
        "container_name": f"checkmk-{full_version}",
        "ports": [f"{port}:5000"],
        "environment": {
            "CMK_SITE_ID": site_id,
            "CMK_PASSWORD": config["admin_password"],
            "CMK_AUTOMATION_SECRET": config["automation_password"],
        },
        "tmpfs": [f"/opt/omd/sites/{site_id}/tmp:uid=1000,gid=1000"],
        "healthcheck": {
            "test": ["CMD", "curl", "-sf", "-u", f"automation:{config['automation_password']}", f"http://localhost:5000/{site_id}/check_mk/api/1.0/version"],
            "interval": "10s",
            "timeout": "5s",
            "retries": 30,
            "start_period": "60s",
        },
        "labels": {
            "checkmk.version": full_version,
            "checkmk.site": site_id,
            "checkmk.api_url": f"http://localhost:{port}/{site_id}/check_mk/api/1.0",
            "checkmk.username": "automation",
        },
        "restart": "unless-stopped",
    }

    # Add bootstrap volumes for custom attributes and automation user
    if include_custom_attrs:
        service["volumes"] = [
            "./testing/custom_attrs.mk:/wato/custom_attrs.mk:ro",
            "./testing/bootstrap-custom-attrs.sh:/docker-entrypoint.d/pre-start/50-custom-attrs.sh:ro",
            "./testing/bootstrap-automation.sh:/docker-entrypoint.d/post-start/60-automation.sh:ro",
        ]

    return service


def dict_to_yaml(data: dict, indent: int = 0) -> str:
    """Convert dict to YAML string (simple implementation)."""
    lines = []
    prefix = "  " * indent

    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"{prefix}{key}:")
            lines.append(dict_to_yaml(value, indent + 1))
        elif isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            for item in value:
                if isinstance(item, dict):
                    # First key on same line as dash
                    first = True
                    for k, v in item.items():
                        if first:
                            lines.append(f"{prefix}  - {k}: {json.dumps(v) if isinstance(v, (dict, list)) else v}")
                            first = False
                        else:
                            lines.append(f"{prefix}    {k}: {json.dumps(v) if isinstance(v, (dict, list)) else v}")
                else:
                    lines.append(f"{prefix}  - {json.dumps(item) if ' ' in str(item) or ':' in str(item) else item}")
        else:
            if isinstance(value, bool):
                value = str(value).lower()
            elif isinstance(value, str) and ('\n' in value or ':' in value or '{' in value):
                # Multi-line or complex string
                value = f'"{value}"' if '\n' not in value else f"|\n{prefix}  " + value.replace('\n', f'\n{prefix}  ')
            lines.append(f"{prefix}{key}: {value}")

    return "\n".join(lines)


def generate_local_compose(config: dict, versions: list[str] = None) -> str:
    """Generate compose file for local multi-container testing."""
    if versions is None:
        versions = list(VERSIONS.keys())

    services = {}
    for v in versions:
        if v not in VERSIONS:
            print(f"Warning: Unknown version {v}, skipping", file=sys.stderr)
            continue
        services[f"checkmk-{v}"] = generate_service(v, VERSIONS[v], config)

    compose = {
        "services": services,
        "networks": {
            "default": {"name": "checkmk-test-network"}
        }
    }

    return COMPOSE_HEADER + dict_to_yaml(compose)


def generate_ci_compose(config: dict, version: str, job_index: int = 0) -> str:
    """Generate compose file for single CI job."""
    if version not in VERSIONS:
        raise ValueError(f"Unknown version: {version}")

    info = VERSIONS[version]
    # Use port offset for parallel CI jobs
    service = generate_service(version, info, config, port_offset=job_index * 100)
    service["container_name"] = f"checkmk-ci-{info['full']}"

    compose = {
        "services": {
            "checkmk": service
        }
    }

    return COMPOSE_HEADER + f"# CI mode: CheckMK {version}\n\n" + dict_to_yaml(compose)


def generate_github_matrix() -> dict:
    """Generate GitHub Actions matrix configuration."""
    return {
        "include": [
            {
                "version": v,
                "full_version": info["full"],
                "port": DEFAULTS["port_base"] + info["port_offset"],
            }
            for v, info in VERSIONS.items()
        ]
    }


def main():
    parser = argparse.ArgumentParser(
        description="Generate Docker Compose for CheckMK testing",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                                    # Local with defaults
  %(prog)s --edition=raw                      # Use free Raw Edition
  %(prog)s --port-base=5000                   # Use ports 5020/5030/5040
  %(prog)s --mode=ci --version=2.4            # CI single container
        """
    )

    # Mode options
    parser.add_argument("--mode", choices=["local", "ci", "matrix"], default="local",
                        help="Generation mode (default: local)")
    parser.add_argument("--version", "-v", help="Version for CI mode (e.g., 2.4)")
    parser.add_argument("--versions", help="Comma-separated versions for local mode")
    parser.add_argument("--output", "-o", help="Output file or directory")
    parser.add_argument("--job-index", type=int, default=0, help="CI job index for port offset")

    # Configuration options
    parser.add_argument("--site-id", default=DEFAULTS["site_id"],
                        help=f"CheckMK site name (default: {DEFAULTS['site_id']})")
    parser.add_argument("--admin-password", default=DEFAULTS["admin_password"],
                        help=f"Web UI password for cmkadmin (default: {DEFAULTS['admin_password']})")
    parser.add_argument("--automation-password", default=DEFAULTS["automation_password"],
                        help=f"API password for automation user (default: {DEFAULTS['automation_password']})")
    parser.add_argument("--edition", choices=["enterprise", "raw"], default=DEFAULTS["edition"],
                        help=f"CheckMK edition (default: {DEFAULTS['edition']})")
    parser.add_argument("--port-base", type=int, default=DEFAULTS["port_base"],
                        help=f"Base port number (default: {DEFAULTS['port_base']})")

    args = parser.parse_args()

    # Build config dict from args
    config = {
        "site_id": args.site_id,
        "admin_password": args.admin_password,
        "automation_password": args.automation_password,
        "edition": args.edition,
        "port_base": args.port_base,
    }

    if args.mode == "local":
        versions = args.versions.split(",") if args.versions else None
        content = generate_local_compose(config, versions)

        if args.output:
            Path(args.output).write_text(content)
            print(f"Generated: {args.output}")
        else:
            print(content)

    elif args.mode == "ci":
        if not args.version:
            parser.error("--version required for CI mode")

        content = generate_ci_compose(config, args.version, args.job_index)

        if args.output:
            output_path = Path(args.output)
            if output_path.is_dir():
                output_path = output_path / f"docker-compose.{args.version}.yml"
            output_path.write_text(content)
            print(f"Generated: {output_path}")
        else:
            print(content)

    elif args.mode == "matrix":
        if args.output:
            output_dir = Path(args.output)
            output_dir.mkdir(parents=True, exist_ok=True)

            # Generate compose file for each version
            for v in VERSIONS:
                content = generate_ci_compose(config, v)
                (output_dir / f"docker-compose.{v}.yml").write_text(content)
                print(f"Generated: {output_dir}/docker-compose.{v}.yml")

            # Generate matrix JSON
            matrix = generate_github_matrix()
            (output_dir / "matrix.json").write_text(json.dumps(matrix, indent=2))
            print(f"Generated: {output_dir}/matrix.json")
        else:
            print(json.dumps(generate_github_matrix(), indent=2))


if __name__ == "__main__":
    main()
